name: sec WF

on: push

jobs:
    build_job:
      runs-on: ubuntu-latest
      steps:
        - name: chckout repo
          uses: actions/checkout@v4
          
        - name: install dragon
          run: sudo apt-get install cowsay -y

        - name: Exec cowsay CMD
          run: cowsay -f dragon "Run for cover,, I am a dragon ..." >> dragon.txt
        
        - name: upload artifacts
          uses: actions/upload-artifact@v3
          with:
            name: dragon-file
            path: dragon.txt

    test-job:
      runs-on: ubuntu-latest
      needs: build_job
      steps:
        - name: download artifact
          uses: actions/download-artifact@v3
          with:
              name: dragon-file

        - name: Test file exists
          run: grep -i "dragon" dragon.txt